apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 076218763980.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 076218763980.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c77642bf
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
